spring:
  application:
    name: apiGw
  cloud:
    gateway:
        routes:
          - id: videoService
            uri: lb://VIDEOSERVICE
            predicates:
              - Path=/api/v1/VideoService/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

